server {
    # Non-root user listens on port 8080
    listen 8080 default_server;
    listen [::]:8080 default_server;

    root /usr/share/nginx/html;
    index index.html;

    server_name _;

    # Serve the frontend files
    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy API requests to the Kubernetes Backend service
    location /api/ {
        # 'backend' will be the name of our Kubernetes Service!
        proxy_pass http://backend:5001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
