{
 "title": "Application Overview",
 "tags": [
  "application",
  "devops"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Application Availability (SLO Target: 99%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status!~\"5..\", namespace=\"devops-app\"}[5m])) / sum(rate(flask_http_request_total{namespace=\"devops-app\"}[5m])) * 100 or on() vector(100)"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{namespace=\"devops-app\"}[1m])) by (status)",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"5..\", namespace=\"devops-app\"}[1m])) or on() vector(0)",
     "legendFormat": "5xx Errors"
    }
   ]
  },
  {
   "title": "Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(flask_http_request_duration_seconds_bucket{namespace=\"devops-app\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{namespace=\"devops-app\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(flask_http_request_duration_seconds_bucket{namespace=\"devops-app\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Backend Pods Resource Usage (CPU & Memory)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"devops-app\", container=\"backend\"}[1m])) by (pod)",
     "legendFormat": "CPU: {{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"devops-app\", container=\"backend\"}) by (pod)",
     "legendFormat": "Memory: {{pod}}"
    }
   ]
  }
 ]
}