{
 "title": "Kubernetes Cluster Health",
 "tags": [
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Nodes Readiness Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "Ready Nodes"
    }
   ]
  },
  {
   "title": "Deployments Replicas Match (Available vs Desired)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"devops-app\"}) / sum(kube_deployment_spec_replicas{namespace=\"devops-app\"}) * 100",
     "legendFormat": "Available %"
    }
   ]
  },
  {
   "title": "Total Pod Restarts in App Namespace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"devops-app\"}[1h]))",
     "legendFormat": "Restarts (Last 1h)"
    }
   ]
  },
  {
   "title": "Pods Health and State",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"devops-app\", phase=\"Running\"} == 1"
    }
   ]
  }
 ]
}