apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-monitor
  namespace: jenkins
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: jenkins
  endpoints:
    - port: http
      path: /prometheus/
      interval: 15s