controller:
  componentName: "jenkins-controller"
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"
    pullPolicy: "Always"
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  installPlugins:
    - "kubernetes"
    - "workflow-aggregator"
    - "git"
    - "configuration-as-code"
    - "job-dsl"
    - "prometheus"
    - "github"
  serviceType: "ClusterIP"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  persistence:
    enabled: true
    storageClass: ""
    size: "8Gi"
  
  env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: docker-secret
          key: docker-username
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: docker-secret
          key: docker-password

  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "CyberBrand Microservices CI/CD Server"
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: "docker-hub-credentials"
                      username: "${DOCKER_USER}"
                      password: "${DOCKER_PASSWORD}"
                      description: "DockerHub Credentials securely injected"
      pipelines: |
        jobs:
          - script: |
              pipelineJob('application-ci') {
                description('Continuous Integration Pipeline: Tests, builds and pushes container images.')
                triggers {
                  githubPush()
                }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/yahali-gottlieb/Project-CyberBrand-K8s-Microservices.git')
                        }
                        branch('*/main')
                      }
                    }
                    scriptPath('Jenkinsfile-ci')
                  }
                }
              }
              pipelineJob('application-cd') {
                description('Continuous Deployment Pipeline: Deploys immutable image tag to Kubernetes.')
                parameters {
                  stringParam('IMAGE_TAG', 'v1', 'The immutable image tag to deploy')
                  stringParam('NAMESPACE', 'devops-app', 'Target Kubernetes Namespace')
                }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/yahali-gottlieb/Project-CyberBrand-K8s-Microservices.git')
                        }
                        branch('*/main')
                      }
                    }
                    scriptPath('Jenkinsfile-cd')
                  }
                }
              }

serviceAccount:
  create: true
  name: jenkins-controller-sa